<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (!Schema::hasColumn('products', 'pricing_matrix')) {
            Schema::table('products', function (Blueprint $table) {
                $table->json('pricing_matrix')->nullable()->after('price');
            });
        }

        $productsData = [
            [
                "name" => "Catylac Exterior Base",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac Base",
                "sub_brand" => "Catylac Exterior",
                "sub_brand1" => "Catylac Exterior",
                "sub_brand2" => "Catylac Exterior Base",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 230000.0, "pail" => 1107000.0],
                    "base_b" => ["tin" => null, "galon" => 213000.0, "pail" => 1020000.0],
                    "base_c" => ["tin" => null, "galon" => 168000.0, "pail" => 835000.0],
                    "base_d" => ["tin" => null, "galon" => 161000.0, "pail" => 797000.0],
                ],
            ],
            [
                "name" => "Catylac Glow Base",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac Base",
                "sub_brand" => "Catylac Glow",
                "sub_brand1" => "Catylac Glow",
                "sub_brand2" => "Catylac Glow Base",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 4.5, "pail" => 22.0, "conversion" => 1.22],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 180000.0, "pail" => 865000.0],
                    "base_b" => ["tin" => null, "galon" => 168000.0, "pail" => 804000.0],
                    "base_c" => ["tin" => null, "galon" => 165000.0, "pail" => 784000.0],
                    "base_d" => ["tin" => null, "galon" => 154000.0, "pail" => 737000.0],
                ],
            ],
            [
                "name" => "Catylac Interior 2in1 Base",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac Base",
                "sub_brand" => "Catylac Interior 2in1",
                "sub_brand1" => "Catylac Interior 2in1",
                "sub_brand2" => "Catylac Interior 2in1 Base",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 196000.0, "pail" => 944000.0],
                    "base_b" => ["tin" => null, "galon" => 192000.0, "pail" => 926000.0],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Interior Base",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac Base",
                "sub_brand" => "Catylac Interior",
                "sub_brand1" => "Catylac Interior",
                "sub_brand2" => "Catylac Interior Base",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 160000.0, "pail" => 761000.0],
                    "base_b" => ["tin" => null, "galon" => 155000.0, "pail" => 744000.0],
                    "base_c" => ["tin" => null, "galon" => 142000.0, "pail" => 680000.0],
                    "base_d" => ["tin" => null, "galon" => 133000.0, "pail" => 641000.0],
                ],
            ],
            [
                "name" => "Catylac Smart Choice Exterior Base",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac Base",
                "sub_brand" => "Catylac Smart Choice Exterior",
                "sub_brand1" => "Catylac Smart Choice Exterior",
                "sub_brand2" => "Catylac Smart Choice Exterior Base",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Smart Choice Interior Base",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac Base",
                "sub_brand" => "Catylac Smart Choice Interior",
                "sub_brand1" => "Catylac Smart Choice Interior",
                "sub_brand2" => "Catylac Smart Choice Interior Base",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Ceiling",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Ceiling",
                "sub_brand1" => "Catylac Ceiling",
                "sub_brand2" => "Catylac Ceiling",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 150000.0, "pail" => 734000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Exterior",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Exterior",
                "sub_brand1" => "Catylac Exterior",
                "sub_brand2" => "Catylac Exterior",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 242000.0, "pail" => 1175000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Glow",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Glow",
                "sub_brand1" => "Catylac Glow",
                "sub_brand2" => "Catylac Glow",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 4.5, "pail" => 22.0, "conversion" => 1.22],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 207000.0, "pail" => 1000000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Hi-Gloss",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Hi-Gloss",
                "sub_brand1" => "Catylac Hi-Gloss",
                "sub_brand2" => "Catylac Hi-Gloss",
                "segment" => "Kg",
                "packaging" => ["tin" => 0.9, "galon" => null, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => 65591.0, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Interior",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Interior",
                "sub_brand1" => "Catylac Interior",
                "sub_brand2" => "Catylac Interior",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 184000.0, "pail" => 892000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Interior 2in1",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Interior 2in1",
                "sub_brand1" => "Catylac Interior 2in1",
                "sub_brand2" => "Catylac Interior 2in1",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 221000.0, "pail" => 1075000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Plamur",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Plamur",
                "sub_brand1" => "Catylac Plamur",
                "sub_brand2" => "Catylac Plamur",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 70000.0, "pail" => 340000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Primer Eksterior",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Exterior Primer",
                "sub_brand1" => "Catylac Primer Eksterior",
                "sub_brand2" => "Catylac Primer Eksterior",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 4.0, "pail" => 21.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 155000.0, "pail" => 783000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Primer Interior",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Interior Primer",
                "sub_brand1" => "Catylac Primer Interior",
                "sub_brand2" => "Catylac Primer Interior",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 4.0, "pail" => 21.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 132000.0, "pail" => 669000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Primer Kayu dan Besi",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Primer Kayu dan Besi",
                "sub_brand1" => "Catylac Primer Kayu dan Besi",
                "sub_brand2" => "Catylac Primer Kayu dan Besi",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.8, "galon" => null, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => 58527.0, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Smart Choice Exterior",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Smart Choice Exterior",
                "sub_brand1" => "Catylac Smart Choice Exterior",
                "sub_brand2" => "Catylac Smart Choice Exterior",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Smart Choice Exterior Primer",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Smart Choice Exterior Primer",
                "sub_brand1" => "Catylac Smart Choice Exterior Primer",
                "sub_brand2" => "Catylac Smart Choice Exterior Primer",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 4.0, "pail" => 20.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Smart Choice Interior",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Smart Choice Interior",
                "sub_brand1" => "Catylac Smart Choice Interior",
                "sub_brand2" => "Catylac Smart Choice Interior",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Catylac Smart Choice Interior Primer",
                "brand" => "Catylac",
                "brand_rm_base" => "Catylac RM",
                "sub_brand" => "Catylac Smart Choice Interior Primer",
                "sub_brand1" => "Catylac Smart Choice Interior Primer",
                "sub_brand2" => "Catylac Smart Choice Interior Primer",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 4.0, "pail" => 20.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Ambiance Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Ambiance",
                "sub_brand1" => "Ambiance",
                "sub_brand2" => "Ambiance Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 347000.0, "pail" => 2477000.0],
                    "base_b" => ["tin" => null, "galon" => 303000.0, "pail" => 2097000.0],
                    "base_c" => ["tin" => null, "galon" => 272000.0, "pail" => 1841000.0],
                    "base_d" => ["tin" => null, "galon" => 259000.0, "pail" => 1827000.0],
                ],
            ],
            [
                "name" => "Ambiance Diamond Glow Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Ambiance",
                "sub_brand1" => "Ambiance Diamond Glow",
                "sub_brand2" => "Ambiance Diamond Glow Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 369000.0, "pail" => 2544000.0],
                    "base_b" => ["tin" => null, "galon" => 322000.0, "pail" => 2197000.0],
                    "base_c" => ["tin" => null, "galon" => 284000.0, "pail" => 1928000.0],
                    "base_d" => ["tin" => null, "galon" => 273000.0, "pail" => 1914000.0],
                ],
            ],
            [
                "name" => "Aquashield Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Aquashield",
                "sub_brand1" => "Aquashield",
                "sub_brand2" => "Aquashield Base",
                "segment" => "Kg",
                "packaging" => ["tin" => 1.0, "galon" => 4.0, "pail" => 20.0, "conversion" => 1.27],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => 74000.0, "galon" => 278000.0, "pail" => 1214000.0],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => 68000.0, "galon" => 252000.0, "pail" => 1105000.0],
                ],
            ],
            [
                "name" => "Aquashield Max Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Aquashield",
                "sub_brand1" => "Aquashield Max",
                "sub_brand2" => "Aquashield Max Base",
                "segment" => "Kg",
                "packaging" => ["tin" => 1.0, "galon" => 4.0, "pail" => 20.0, "conversion" => 1.27],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => 78000.0, "galon" => 297000.0, "pail" => 1597000.0],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => 72000.0, "galon" => 270000.0, "pail" => 1182000.0],
                ],
            ],
            [
                "name" => "Easy Clean Anti - Viral Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Easy Clean",
                "sub_brand1" => "Easy Clean",
                "sub_brand2" => "Easy Clean Anti - Viral Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 315000.0, "pail" => 2242000.0],
                    "base_b" => ["tin" => null, "galon" => 263000.0, "pail" => 1879000.0],
                    "base_c" => ["tin" => null, "galon" => 240000.0, "pail" => 1653000.0],
                    "base_d" => ["tin" => null, "galon" => 227000.0, "pail" => 1611000.0],
                ],
            ],
            [
                "name" => "Easy Clean Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Easy Clean",
                "sub_brand1" => "Easy Clean",
                "sub_brand2" => "Easy Clean Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Pearl Glo Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Others",
                "sub_brand1" => "Pearl Glo",
                "sub_brand2" => "Pearl Glo Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Pentalite Antibac Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Pentalite",
                "sub_brand1" => "Pentalite",
                "sub_brand2" => "Pentalite Antibac Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 256000.0, "pail" => 1837000.0],
                    "base_b" => ["tin" => null, "galon" => 217000.0, "pail" => 1570000.0],
                    "base_c" => ["tin" => null, "galon" => 192000.0, "pail" => 1320000.0],
                    "base_d" => ["tin" => null, "galon" => 179000.0, "pail" => 1214000.0],
                ],
            ],
            [
                "name" => "Pentalite Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Pentalite",
                "sub_brand1" => "Pentalite",
                "sub_brand2" => "Pentalite Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Powerflexx Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Powerflexx",
                "sub_brand1" => "Powerflexx",
                "sub_brand2" => "Powerflexx Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Powerflexx Next Gen Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Powerflexx",
                "sub_brand1" => "Powerflexx Next Gen",
                "sub_brand2" => "Powerflexx Next Gen Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 470000.0, "pail" => 3266000.0],
                    "base_b" => ["tin" => null, "galon" => 409000.0, "pail" => 2950000.0],
                    "base_c" => ["tin" => null, "galon" => 386000.0, "pail" => 2656000.0],
                    "base_d" => ["tin" => null, "galon" => 367000.0, "pail" => 2549000.0],
                ],
            ],
            [
                "name" => "V-Gloss Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "V-Gloss",
                "sub_brand1" => "V-Gloss",
                "sub_brand2" => "V-Gloss Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.8, "galon" => 2.4, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "V-Gloss High Gloss Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "V-Gloss High Gloss",
                "sub_brand1" => "V-Gloss High Gloss",
                "sub_brand2" => "V-Gloss High Gloss Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.8, "galon" => 2.4, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => 73000.0, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => 73000.0, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => 73000.0, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => 73000.0, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Weathershield",
                "sub_brand1" => "Weathershield",
                "sub_brand2" => "Weathershield Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Core Dualshield Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Weathershield",
                "sub_brand1" => "Weathershield Core Dualshield",
                "sub_brand2" => "Weathershield Core Dualshield Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 416000.0, "pail" => 2972000.0],
                    "base_b" => ["tin" => null, "galon" => 371000.0, "pail" => 2649000.0],
                    "base_c" => ["tin" => null, "galon" => 345000.0, "pail" => 2350000.0],
                    "base_d" => ["tin" => null, "galon" => 321000.0, "pail" => 2220000.0],
                ],
            ],
            [
                "name" => "Weathershield Dirt Resistance Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Weathershield",
                "sub_brand1" => "Weathershield Dirt Resistance",
                "sub_brand2" => "Weathershield Dirt Resistance Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 437000.0, "pail" => 3121000.0],
                    "base_b" => ["tin" => null, "galon" => 390000.0, "pail" => 2781000.0],
                    "base_c" => ["tin" => null, "galon" => 362000.0, "pail" => 2468000.0],
                    "base_d" => ["tin" => null, "galon" => 337000.0, "pail" => 2331000.0],
                ],
            ],
            [
                "name" => "Weathershield Flash Base",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux Base",
                "sub_brand" => "Weathershield Flash",
                "sub_brand1" => "Weathershield Flash",
                "sub_brand2" => "Weathershield Flash Base",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => 443000.0, "pail" => 3050000.0],
                    "base_b" => ["tin" => null, "galon" => 389000.0, "pail" => 2806000.0],
                    "base_c" => ["tin" => null, "galon" => 377000.0, "pail" => 2601000.0],
                    "base_d" => ["tin" => null, "galon" => 359000.0, "pail" => 2493000.0],
                ],
            ],
            [
                "name" => "Alkali Killer",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Alkali Killer",
                "sub_brand1" => "Alkali Killer",
                "sub_brand2" => "Alkali Killer",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 236000.0, "pail" => 1631000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Alkali Resisting Primer",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Alkali Resisting Primer",
                "sub_brand1" => "Alkali Resisting Primer",
                "sub_brand2" => "Alkali Resisting Primer",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 167000.0, "pail" => 1355000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Ambiance",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Ambiance",
                "sub_brand1" => "Ambiance",
                "sub_brand2" => "Ambiance",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 377000.0, "pail" => 2645000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Ambiance Diamond Glow",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Ambiance",
                "sub_brand1" => "Ambiance Diamond Glow",
                "sub_brand2" => "Ambiance Diamond Glow",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 399000.0, "pail" => 2824000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Aquashield",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Aquashield",
                "sub_brand1" => "Aquashield",
                "sub_brand2" => "Aquashield",
                "segment" => "Kg",
                "packaging" => ["tin" => 1.0, "galon" => 4.0, "pail" => 20.0, "conversion" => 1.27],
                "prices" => [
                    "rm" => ["tin" => 81000.0, "galon" => 234000.0, "pail" => 1346000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Aquashield 2K",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Aquashield",
                "sub_brand1" => "Aquashield 2K",
                "sub_brand2" => "Aquashield 2K",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 143000.0, "pail" => 480000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Aquashield Max",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Aquashield",
                "sub_brand1" => "Aquashield Max",
                "sub_brand2" => "Aquashield Max",
                "segment" => "Kg",
                "packaging" => ["tin" => 1.0, "galon" => 4.0, "pail" => 20.0, "conversion" => 1.27],
                "prices" => [
                    "rm" => ["tin" => 87000.0, "galon" => 331000.0, "pail" => 1437000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Ceiling",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Ceiling",
                "sub_brand1" => "Ceiling",
                "sub_brand2" => "Ceiling",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 5.0, "pail" => 25.0, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 228000.0, "pail" => 1102000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Easy Clean",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Easy Clean",
                "sub_brand1" => "Easy Clean",
                "sub_brand2" => "Easy Clean",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Easy Clean Anti - Viral",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Easy Clean",
                "sub_brand1" => "Easy Clean",
                "sub_brand2" => "Easy Clean Anti - Viral",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 339000.0, "pail" => 2300000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Hammerite - DTG",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Hammerite - DTG",
                "sub_brand1" => "Hammerite - DTG",
                "sub_brand2" => "Hammerite - DTG",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.25, "galon" => 0.75, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Hammerite Thinner",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Hammerite Thinner",
                "sub_brand1" => "Hammerite Thinner",
                "sub_brand2" => "Hammerite Thinner",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.25, "galon" => 0.75, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Pentalite",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Pentalite",
                "sub_brand1" => "Pentalite",
                "sub_brand2" => "Pentalite",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Pentalite Antibac",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Pentalite",
                "sub_brand1" => "Pentalite",
                "sub_brand2" => "Pentalite Antibac",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 272000.0, "pail" => 2064000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Pentalite Light & Space",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Others",
                "sub_brand1" => "Pentalite Light & Space",
                "sub_brand2" => "Pentalite Light & Space",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 215000.0, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Powerflexx",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Powerflexx",
                "sub_brand1" => "Powerflexx",
                "sub_brand2" => "Powerflexx",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Powerflexx Next Gen",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Powerflexx",
                "sub_brand1" => "Powerflexx Next Gen",
                "sub_brand2" => "Powerflexx Next Gen",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 480000.0, "pail" => 3436000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Thinner",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Others",
                "sub_brand1" => "Thinner",
                "sub_brand2" => "Thinner",
                "segment" => "Ltr",
                "packaging" => ["tin" => 1.0, "galon" => null, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => 41000.0, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "V-Gloss",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "V-Gloss",
                "sub_brand1" => "V-Gloss",
                "sub_brand2" => "V-Gloss",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.8, "galon" => 2.4, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "V-Gloss Doff",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "V-Gloss Doff",
                "sub_brand1" => "V-Gloss Doff",
                "sub_brand2" => "V-Gloss Doff",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.8, "galon" => 2.4, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "V-Gloss High Gloss",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "V-Gloss High Gloss",
                "sub_brand1" => "V-Gloss High Gloss",
                "sub_brand2" => "V-Gloss High Gloss",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.8, "galon" => 2.4, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Wallfiller",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Others",
                "sub_brand1" => "Wallfiller",
                "sub_brand2" => "Wallfiller",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 3.5, "pail" => null, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 108150.0, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield",
                "sub_brand1" => "Weathershield",
                "sub_brand2" => "Weathershield",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Core Dualshield",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield",
                "sub_brand1" => "Weathershield Core Dualshield",
                "sub_brand2" => "Weathershield Core Dualshield",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 453000.0, "pail" => 3245000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Dirt Resistance",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield",
                "sub_brand1" => "Weathershield Dirt Resistance",
                "sub_brand2" => "Weathershield Dirt Resistance",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 460000.0, "pail" => 3337000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Flash",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield Flash",
                "sub_brand1" => "Weathershield Flash",
                "sub_brand2" => "Weathershield Flash",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 469000.0, "pail" => 3429000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Gloss",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield Gloss",
                "sub_brand1" => "Weathershield Gloss",
                "sub_brand2" => "Weathershield Gloss",
                "segment" => "Ltr",
                "packaging" => ["tin" => 0.9, "galon" => null, "pail" => null, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Power Sealer",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield Power Sealer",
                "sub_brand1" => "Weathershield Power Sealer",
                "sub_brand2" => "Weathershield Power Sealer",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 218300.0, "pail" => 1619000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Primer",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield Primer",
                "sub_brand1" => "Weathershield Primer",
                "sub_brand2" => "Weathershield Primer",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 208000.0, "pail" => 1542000.0],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Putty",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield Putty",
                "sub_brand1" => "Weathershield Putty",
                "sub_brand2" => "Weathershield Putty",
                "segment" => "Kg",
                "packaging" => ["tin" => 3.5, "galon" => null, "pail" => null, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 166000.0, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Weathershield Roof Paint",
                "brand" => "Dulux",
                "brand_rm_base" => "Dulux RM",
                "sub_brand" => "Weathershield Roof Paint",
                "sub_brand1" => "Weathershield Roof Paint",
                "sub_brand2" => "Weathershield Roof Paint",
                "segment" => "Ltr",
                "packaging" => ["tin" => null, "galon" => 2.5, "pail" => 20.0, "conversion" => null],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => 273000.0, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
            [
                "name" => "Maxilite",
                "brand" => "Maxilite",
                "brand_rm_base" => "Maxilite",
                "sub_brand" => "Others",
                "sub_brand1" => "Maxilite",
                "sub_brand2" => "Maxilite",
                "segment" => "Kg",
                "packaging" => ["tin" => null, "galon" => 4.5, "pail" => 18.5, "conversion" => 1.4],
                "prices" => [
                    "rm" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_a" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_b" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_c" => ["tin" => null, "galon" => null, "pail" => null],
                    "base_d" => ["tin" => null, "galon" => null, "pail" => null],
                ],
            ],
        ];

        foreach ($productsData as $data) {
            $matrix = [
                'brand' => $data['brand'],
                'brand_rm_base' => $data['brand_rm_base'],
                'sub_brand' => $data['sub_brand'],
                'sub_brand1' => $data['sub_brand1'],
                'sub_brand2' => $data['sub_brand2'],
                'segment' => $data['segment'],
                'packaging' => $data['packaging'],
                'prices' => $data['prices'],
            ];

            // Match by name or partial name
            $name = $data['name'];
            $cleanName = strtolower(trim($name));

            $matched = DB::table('products')
                ->whereRaw('LOWER(TRIM(name)) = ?', [$cleanName])
                ->first();

            if ($matched) {
                DB::table('products')->where('id', $matched->id)->update([
                    'pricing_matrix' => json_encode($matrix),
                ]);
            } else {
                // Try fuzzy match
                $matchedFuzzy = DB::table('products')
                    ->where(function ($q) use ($name) {
                        $q->where('name', 'LIKE', '%' . $name . '%')
                          ->orWhere('sku_code', 'LIKE', '%' . str_replace(' ', '-', strtoupper($name)) . '%');
                    })
                    ->first();

                if ($matchedFuzzy) {
                    DB::table('products')->where('id', $matchedFuzzy->id)->update([
                        'pricing_matrix' => json_encode($matrix),
                    ]);
                }
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        if (Schema::hasColumn('products', 'pricing_matrix')) {
            Schema::table('products', function (Blueprint $table) {
                $table->dropColumn('pricing_matrix');
            });
        }
    }
};
