<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CompetitorProduct;
use App\Models\Principal;

class CompetitorProductSeeder extends Seeder
{
    public function run(): void
    {
        $duluxPrincipal = Principal::where('code', 'LIKE', '%DULUX%')
            ->orWhere('name', 'LIKE', '%DULUX%')
            ->orWhere('name', 'LIKE', '%ICI%')
            ->orWhere('subdomain', 'dulux')
            ->first();

        $principalId = $duluxPrincipal ? $duluxPrincipal->id : null;

        $products = [
            // JOTUN
            [
                'brand' => 'JOTUN',
                'subbrand' => 'Majestic True Beauty Matt / Sheen',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Tin (0.9L / 1L)', 'Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 125000,
                'benchmark_price_galon' => 285000,
                'benchmark_price_pail' => 2150000,
                'order_index' => 1,
            ],
            [
                'brand' => 'JOTUN',
                'subbrand' => 'Majestic Perfect Beauty & Care',
                'category' => 'Interior Super Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 340000,
                'benchmark_price_pail' => 2580000,
                'order_index' => 2,
            ],
            [
                'brand' => 'JOTUN',
                'subbrand' => 'Jotashield Antifade Colours',
                'category' => 'Eksterior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 375000,
                'benchmark_price_pail' => 2850000,
                'order_index' => 3,
            ],
            [
                'brand' => 'JOTUN',
                'subbrand' => 'Jotashield Infinity / Extreme',
                'category' => 'Eksterior Super Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 450000,
                'benchmark_price_pail' => 3450000,
                'order_index' => 4,
            ],
            [
                'brand' => 'JOTUN',
                'subbrand' => 'Essence Cover Plus',
                'category' => 'Interior Medium',
                'packaging_sizes' => ['Galon (3.5L / 4L)', 'Pail (18L / 20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 195000,
                'benchmark_price_pail' => 980000,
                'order_index' => 5,
            ],
            [
                'brand' => 'JOTUN',
                'subbrand' => 'Essence Tough Shield',
                'category' => 'Eksterior Medium',
                'packaging_sizes' => ['Galon (3.5L / 4L)', 'Pail (18L / 20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 245000,
                'benchmark_price_pail' => 1250000,
                'order_index' => 6,
            ],
            [
                'brand' => 'JOTUN',
                'subbrand' => 'Gardex Premium Gloss',
                'category' => 'Wood & Metal',
                'packaging_sizes' => ['Tin (0.9L)', 'Galon (2.5L)'],
                'benchmark_price_tin' => 88000,
                'benchmark_price_galon' => 235000,
                'benchmark_price_pail' => 0,
                'order_index' => 7,
            ],
            [
                'brand' => 'JOTUN',
                'subbrand' => 'WaterGuard',
                'category' => 'Waterproofing',
                'packaging_sizes' => ['Galon (4L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 215000,
                'benchmark_price_pail' => 1020000,
                'order_index' => 8,
            ],

            // NIPPON PAINT
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Vinilex Regular (White & Color)',
                'category' => 'Interior Medium',
                'packaging_sizes' => ['Tin (1Kg)', 'Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 45000,
                'benchmark_price_galon' => 165000,
                'benchmark_price_pail' => 765000,
                'order_index' => 9,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Vinilex Silver-Ion',
                'category' => 'Interior Medium Plus',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 195000,
                'benchmark_price_pail' => 895000,
                'order_index' => 10,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Spot-less (Anti Noda)',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 275000,
                'benchmark_price_pail' => 2050000,
                'order_index' => 11,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Spot-less Plus',
                'category' => 'Interior Premium Plus',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 310000,
                'benchmark_price_pail' => 2350000,
                'order_index' => 12,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Weatherbond',
                'category' => 'Eksterior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 345000,
                'benchmark_price_pail' => 2650000,
                'order_index' => 13,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Weatherbond Solareflect',
                'category' => 'Eksterior Super Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 420000,
                'benchmark_price_pail' => 3200000,
                'order_index' => 14,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Satin Glo',
                'category' => 'Interior Premium (Kilap Lembut)',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 295000,
                'benchmark_price_pail' => 2200000,
                'order_index' => 15,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Elastex Waterproof 3-in-1',
                'category' => 'Waterproofing',
                'packaging_sizes' => ['Galon (4Kg)', 'Pail (20Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 210000,
                'benchmark_price_pail' => 990000,
                'order_index' => 16,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Platone 8000 / Bee Brand',
                'category' => 'Wood & Metal',
                'packaging_sizes' => ['Tin (0.9L / 1L)', 'Galon (3.78L)'],
                'benchmark_price_tin' => 75000,
                'benchmark_price_galon' => 280000,
                'benchmark_price_pail' => 0,
                'order_index' => 17,
            ],
            [
                'brand' => 'NIPPON PAINT',
                'subbrand' => 'Matex Gold / Matex Maxi',
                'category' => 'Interior Economy',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 120000,
                'benchmark_price_pail' => 540000,
                'order_index' => 18,
            ],

            // AVIAN / NO DROP / LENKOTE
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'Sunguard All-in-One',
                'category' => 'Eksterior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 335000,
                'benchmark_price_pail' => 2550000,
                'order_index' => 19,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'Supersilk Anti Noda',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 265000,
                'benchmark_price_pail' => 1950000,
                'order_index' => 20,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'Everglo (Satin Luxury)',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 285000,
                'benchmark_price_pail' => 2100000,
                'order_index' => 21,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'Avitex Interior',
                'category' => 'Interior Medium',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 145000,
                'benchmark_price_pail' => 675000,
                'order_index' => 22,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'Avitex Gold / Anti Bakteri',
                'category' => 'Interior Medium Plus',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 175000,
                'benchmark_price_pail' => 810000,
                'order_index' => 23,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'No Drop (Pelapis Anti Bocor)',
                'category' => 'Waterproofing',
                'packaging_sizes' => ['Tin (1Kg)', 'Galon (4Kg)', 'Pail (20Kg)'],
                'benchmark_price_tin' => 58000,
                'benchmark_price_galon' => 205000,
                'benchmark_price_pail' => 975000,
                'order_index' => 24,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'No Drop Tinting',
                'category' => 'Waterproofing Tinting',
                'packaging_sizes' => ['Galon (4Kg)', 'Pail (20Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 235000,
                'benchmark_price_pail' => 1120000,
                'order_index' => 25,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'Avian Cat Kayu & Besi',
                'category' => 'Wood & Metal',
                'packaging_sizes' => ['Tin (0.9L / 1L)'],
                'benchmark_price_tin' => 72000,
                'benchmark_price_galon' => 0,
                'benchmark_price_pail' => 0,
                'order_index' => 26,
            ],
            [
                'brand' => 'AVIAN / NO DROP / LENKOTE',
                'subbrand' => 'Aries / Aries Gold',
                'category' => 'Interior Economy',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (20Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 75000,
                'benchmark_price_pail' => 280000,
                'order_index' => 27,
            ],

            // MOWILEX
            [
                'brand' => 'MOWILEX',
                'subbrand' => 'Weathercoat Regular',
                'category' => 'Eksterior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 365000,
                'benchmark_price_pail' => 2750000,
                'order_index' => 28,
            ],
            [
                'brand' => 'MOWILEX',
                'subbrand' => 'Weathercoat Supreme',
                'category' => 'Eksterior Super Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 460000,
                'benchmark_price_pail' => 3500000,
                'order_index' => 29,
            ],
            [
                'brand' => 'MOWILEX',
                'subbrand' => 'Emulsion (Interior Premium)',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Tin (1L)', 'Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 110000,
                'benchmark_price_galon' => 255000,
                'benchmark_price_pail' => 1950000,
                'order_index' => 30,
            ],
            [
                'brand' => 'MOWILEX',
                'subbrand' => 'Cendana Interior',
                'category' => 'Interior Medium',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 160000,
                'benchmark_price_pail' => 740000,
                'order_index' => 31,
            ],
            [
                'brand' => 'MOWILEX',
                'subbrand' => 'Cendana Exterior',
                'category' => 'Eksterior Medium',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 230000,
                'benchmark_price_pail' => 1100000,
                'order_index' => 32,
            ],
            [
                'brand' => 'MOWILEX',
                'subbrand' => 'WP02 Waterproof',
                'category' => 'Waterproofing',
                'packaging_sizes' => ['Galon (4Kg)', 'Pail (20Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 225000,
                'benchmark_price_pail' => 1050000,
                'order_index' => 33,
            ],
            [
                'brand' => 'MOWILEX',
                'subbrand' => 'Acrylic Gloss Enamel',
                'category' => 'Wood & Metal',
                'packaging_sizes' => ['Tin (1L)'],
                'benchmark_price_tin' => 95000,
                'benchmark_price_galon' => 0,
                'benchmark_price_pail' => 0,
                'order_index' => 34,
            ],

            // PROPAN
            [
                'brand' => 'PROPAN',
                'subbrand' => 'Decorshield',
                'category' => 'Eksterior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 325000,
                'benchmark_price_pail' => 2450000,
                'order_index' => 35,
            ],
            [
                'brand' => 'PROPAN',
                'subbrand' => 'Decorcryl',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 245000,
                'benchmark_price_pail' => 1850000,
                'order_index' => 36,
            ],
            [
                'brand' => 'PROPAN',
                'subbrand' => 'Decorlotus',
                'category' => 'Interior Super Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 295000,
                'benchmark_price_pail' => 2250000,
                'order_index' => 37,
            ],
            [
                'brand' => 'PROPAN',
                'subbrand' => 'Eco Emulsion',
                'category' => 'Interior Medium',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 140000,
                'benchmark_price_pail' => 650000,
                'order_index' => 38,
            ],
            [
                'brand' => 'PROPAN',
                'subbrand' => 'Ultraproof',
                'category' => 'Waterproofing',
                'packaging_sizes' => ['Galon (4Kg)', 'Pail (20Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 205000,
                'benchmark_price_pail' => 960000,
                'order_index' => 39,
            ],
            [
                'brand' => 'PROPAN',
                'subbrand' => 'GoFast A-1000',
                'category' => 'Wood & Metal',
                'packaging_sizes' => ['Tin (0.9L)'],
                'benchmark_price_tin' => 78000,
                'benchmark_price_galon' => 0,
                'benchmark_price_pail' => 0,
                'order_index' => 40,
            ],

            // KANSAI / DANAPAINT
            [
                'brand' => 'KANSAI / DANAPAINT',
                'subbrand' => 'Sincere',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 240000,
                'benchmark_price_pail' => 1800000,
                'order_index' => 41,
            ],
            [
                'brand' => 'KANSAI / DANAPAINT',
                'subbrand' => 'Ruby',
                'category' => 'Interior Medium',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 135000,
                'benchmark_price_pail' => 620000,
                'order_index' => 42,
            ],
            [
                'brand' => 'KANSAI / DANAPAINT',
                'subbrand' => 'Danacryl',
                'category' => 'Interior Premium',
                'packaging_sizes' => ['Galon (2.5L)', 'Pail (20L)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 260000,
                'benchmark_price_pail' => 1950000,
                'order_index' => 43,
            ],
            [
                'brand' => 'KANSAI / DANAPAINT',
                'subbrand' => 'Danagloss',
                'category' => 'Wood & Metal / Enamel',
                'packaging_sizes' => ['Tin (1L)'],
                'benchmark_price_tin' => 85000,
                'benchmark_price_galon' => 0,
                'benchmark_price_pail' => 0,
                'order_index' => 44,
            ],
            [
                'brand' => 'KANSAI / DANAPAINT',
                'subbrand' => 'Rainkote',
                'category' => 'Waterproofing',
                'packaging_sizes' => ['Galon (4Kg)', 'Pail (20Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 195000,
                'benchmark_price_pail' => 920000,
                'order_index' => 45,
            ],

            // PACIFIC PAINT
            [
                'brand' => 'PACIFIC PAINT',
                'subbrand' => 'Metrolite',
                'category' => 'Interior Medium',
                'packaging_sizes' => ['Galon (3L / 5Kg)', 'Pail (16L / 25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 130000,
                'benchmark_price_pail' => 600000,
                'order_index' => 46,
            ],
            [
                'brand' => 'PACIFIC PAINT',
                'subbrand' => 'Glotex',
                'category' => 'Wood & Metal',
                'packaging_sizes' => ['Tin (1L)'],
                'benchmark_price_tin' => 68000,
                'benchmark_price_galon' => 0,
                'benchmark_price_pail' => 0,
                'order_index' => 47,
            ],
            [
                'brand' => 'PACIFIC PAINT',
                'subbrand' => 'Finatex',
                'category' => 'Interior Economy',
                'packaging_sizes' => ['Galon (5Kg)', 'Pail (25Kg)'],
                'benchmark_price_tin' => 0,
                'benchmark_price_galon' => 70000,
                'benchmark_price_pail' => 260000,
                'order_index' => 48,
            ],
        ];

        foreach ($products as $item) {
            CompetitorProduct::updateOrCreate(
                [
                    'brand' => $item['brand'],
                    'subbrand' => $item['subbrand'],
                ],
                array_merge($item, [
                    'principal_id' => $principalId,
                    'is_active' => true,
                ])
            );
        }
    }
}
